version: 1
formatters:
  simple:
    format: '%(asctime)s:%(levelname)s:%(module)s:%(funcName)s: %(message)s'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: cipher-event-logger.log
    maxBytes: 10485760
    backupCount: 1
    encoding: utf8
    mode: w
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  cipher-event-logger:
    level: DEBUG
    handlers: [file]
    propagate: no

